In [44]:
import numpy as np

epochs = 10

class HopfieldNetwork:

  def __init__(self, size):
    self.size = size
    self.weights = np.zeros((size,size))

  def train(self, patterns):

    for pattern in patterns:

      p = pattern.reshape(-1,1) #Into Column Vector

      self.weights += np.dot(p, p.T)

    np.fill_diagonal(self.weights, 0)

  def call(self, inputs, num_iterations = 10):
    assert len(inputs) == self.size
    current_state = inputs.copy()

    for _ in range(num_iterations):

      for i in range(self.size):

        h = np.dot(self.weights[i], current_state)

        current_state[i] = 1 if h>0 else -1

      if current_state in patterns:
        break

    return current_state







In [45]:
network = HopfieldNetwork(4)

patterns = [[1,1,1,1],
            [-1,-1,1,1],]

patterns = np.array(patterns)

for i in range(epochs):
  network.train(patterns)

print(network.weights)

[[ 0. 20.  0.  0.]
 [20.  0.  0.  0.]
 [ 0.  0.  0. 20.]
 [ 0.  0. 20.  0.]]


In [46]:
print(network.call([-1,-1,-1,1]))

[-1, -1, 1, 1]
